---
- hosts: all
  connection: httpapi
  tasks:

    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain


# update.. testing.. playing..
    - name: Execute 'createMultipleNetworkObject' operation
      cisco.fmcansible.fmc_configuration:
        operation: "createMultipleNetworkObject"
        data:
            name: net1
            value: 1.0.0.0/24
            overridable: False
            description: Network obj 1
            type: Network

#            name: net2
#            value: 1.1.0.0/24
#            overridable: False
#            description: Network obj 2
#            type: Network

        path_params:
            domainUUID: "{{ domain[0].uuid }}"
#        query_params:
#            bulk: "{{ bulk }}"
        register_as: create_object


    - name: Timmay HARD STOP this Playbook
      meta: end_play


    - name: Create a network object for Cisco FTD 1
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleNetworkObject
        data:
          type: Network
          name: "{{ name }}"
          value: "{{ value }}"
          description: "{{ description }}"
        path_params:
          domainUUID: "{{ domain[0].uuid }}"
        register_as: create_object
