---
- hosts: all
  connection: httpapi
  tasks:
    - name: 01 - Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains

    - name: 02 - Debug domain_response
      debug:
        var: domains

    - name: 03 - Set domain_uuid
      set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"
