---
# NEW
- name: Obtain and display the current date, time, and timezone
  hosts: localhost
  gather_facts: true  # Set this to true to gather facts including date and time

  tasks:
    - name: Obtain the current date and time
      set_fact:
        current_datetime: "{{ ansible_date_time.iso8601 }}"

    - name: Print the current date and time
      debug:
        msg: "Current date and time: {{ current_datetime }}"

    - name: Obtain the current timezone
      set_fact:
        current_timezone: "{{ ansible_date_time.tz }}"

    - name: Print the current timezone
      debug:
        msg: "Current timezone: {{ current_timezone }}"


