---
- name: Playbook to get the expiry date of the RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: true

  tasks:

    - name: 01 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains

#    - name: Print
#      debug:
#        var: domains
#
#    - name: 0x - Get Domain
#      cisco.fmcansible.fmc_configuration:
#        operation: getAllDomain
#      register: domains_register
#
#    - name: Print
#      debug:
#        var: domains_register


    - name: 02 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"

    - name: 03 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: response



    - name: 04 - Set expiry date fact
      ansible.builtin.set_fact:
        expiry_date: "{{ response['response']['items'][0]['certEnrollments'][0]['certificateInfo']['expiry'] }}"

    - name: 05 - Obtain Current Time
      ansible.builtin.set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: 06 - Calculate difference between expiry date and today
      set_fact:
        days_until_expiry: "{{ (expiry_date | to_datetime('%Y-%m-%dT%H:%M:%SZ') - current_date | to_datetime('%Y-%m-%dT%H:%M:%SZ')).days }}"

    - name: 07 - End playbook if certificate expiry is more than 30 days away
      ansible.builtin.meta: end_play
      when: days_until_expiry | int > 30

    - name: 08 - Run next task if certificate expiry is less than 30 days
      debug:
        msg: "Certificate expires in {{ days_until_expiry }} days, running the next task."
      when: days_until_expiry <= 30


########################################################################
########################################################################
########################################################################
########################################################################

    - name: 04 - Set expiry date fact
      ansible.builtin.set_fact:
        expiry_date: "{{ response['response']['items'][0]['certEnrollments'][0]['certificateInfo']['expiry'] }}"

    - name: 04z DO NOT REMOVE -- Debug the date returned from the FMC
      ansible.builtin.debug:
        msg: "Object evaluated is {{ expiry_date.__class__.__name__ }} and value {{ expiry_date }}"

    - name: 05 - Obtain Current Time
      ansible.builtin.set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"


#    - name: 05z DO NOT REMOVE -- Debug the date returned from the FMC
#      ansible.builtin.debug:
#        msg: "Object evaluated is {{ current_date.__class__.__name__ }} and value {{ current_date }}"


#    - debug:
#        var: (expiry_date | to_datetime("%Y-%m-%dT%H:%M:%SZ")) - (current_date | to_datetime("%Y-%m-%dT%H:%M:%SZ"))


    - name: 06 - Calculate difference between expiry date and today
      set_fact:
        days_until_expiry: "{{ (expiry_date | to_datetime('%Y-%m-%dT%H:%M:%SZ')) - (current_date | to_datetime('%Y-%m-%dT%H:%M:%SZ')) }}"
#       days_until_expiry: "{{ (current_date | to_datetime("%Y-%m-%dT%H:%M:%SZ"))" - "(expiry_date | to_datetime("%Y-%m-%dT%H:%M:%SZ")) }}
 

    - name: Print
      debug:
        var: days_until_expiry

#    - debug:
#        msg: 
#        - "{{ days_until_expiry }}"
#        - "{{ days_until_expiry | type_debug }}"



    - name: Extract expiry date and calculate days remaining
      set_fact:
        expiry_date: "{{ response.response.items[0].certEnrollments[0].certificateInfo.expiry }}"
        days_remaining: "{{ (expiry_date | to_datetime('%Y-%m-%dT%H:%M:%SZ') - lookup('pipe', 'date +%Y-%m-%dT%H:%M:%SZ' | to_datetime('%Y-%m-%dT%H:%M:%SZ'))).days }}"
      
    - name: Debug expiry date and days remaining
      debug:
        msg:
          - "Certificate Expiry Date: {{ expiry_date }}"
          - "Days Remaining: {{ days_remaining }}"

    - name: End playbook if the certificate is valid for more than 30 days
      meta: end_play
      when: days_remaining > 30

    - name: Proceed with the next task (cert expiry in less than 30 days)
      debug:
        msg: "The certificate is expiring in {{ days_remaining }} days and needs to be renewed."
      when: days_remaining <= 30




    - name: Timmay HARD STOP this Playbook
      meta: end_play







    - name: Set fact based on days_until_expiry
      ansible.builtin.set_fact:
        action: "{{ 'go_forward' if days_until_expiry <= 30 else 'stop' }}"




    - name: 09 - Check if the expiry date is before today or within 30 days
      debug:
        msg: >
          {% if days_until_expiry < 0 %}
          The certificate has already expired.
          {% elif days_until_expiry <= 30 %}
          The certificate will expire within the next 30 days.
          {% else %}
          The certificate is valid for more than 30 days.
          {% endif %}




#    - debug:
#        var: ( current_date | to_datetime("%Y-%m-%dT%H:%M:%SZ") - expiry_date | to_datetime("%Y-%m-%dT%H:%M:%SZ")).total_seconds()

#    - debug:
#        msg: "dates are within 30 days"
#      when: ( current_date | to_datetime("%Y-%m-%dT%H:%M:%SZ") - expiry_date | to_datetime("%Y-%m-%dT%H:%M:%SZ")) < 86400*30 

##
##  Delete everything below here
##


#    - name: 05a - Convert expiry_date to yaml
#      set_fact:
#        expiry_date_yaml: "{{ expiry_date | from_yaml }}"
#
#    - name: 05az DO NOT REMOVE -- Debug an Object
#      debug:
#        msg: "Object evaluated is {{ expiry_date_yaml.__class__.__name__ }} and value {{ expiry_date_yaml }}"
#
#
#
#    - name: 05b - Convert yaml to datetime object
#      set_fact:
#        expiry_date_datetime: "{{ expiry_date_yaml | to_datetime }}"
#
#    - name: 05bz DO NOT REMOVE -- Debug an Object
#      debug:
#        msg: "Object evaluated is {{ expiry_date_datetime.__class__.__name__ }} and value {{ expiry_date_datetime }}"






    - name: 05 - Remove T and Z from expiry_date
      set_fact:
        cleaned_expiry_date: "{{ expiry_date | regex_replace('T', ' ') | regex_replace('Z', '') }}"

    - name: 06 - Parse Expiry Date string to Date Object
      set_fact:
        expiry_date_obj: "{{ cleaned_expiry_date | to_datetime('%Y-%m-%d %H:%M:%S') }}"

#   - name: 06y - Create a fact out of shittext
#      set_fact:
#        cleaned_expiry_date: "{{ "2016-08-14 20:00:12" | to_datetime }}"
#        expiry_date_obj: "{{ cleaned_expiry_date | to_datetime('%Y-%m-%d %H:%M:%S') }}"

    - name: 06z DO NOT REMOVE -- Debug an Object
      debug:
        msg: "Object evaluated is {{ expiry_date_obj.__class__.__name__ }} and value {{ expiry_date_obj }}"


    - name: Timmay HARD STOP this Playbook
      meta: end_play



    - name: 05 - Convert Expiry Date string to Date Object
      set_fact:
        expiry_date_obj: "{{ expiry_date | from_yaml | strftime('%Y-%m-%d') }}"

    - name: Timmay HARD STOP this Playbook
      meta: end_play


#
#
# 

# ChatGPT states we should remove this. 
#    - name: 05 - Convert Expiry Date string to DateTime Object
#      set_fact:
#        expiry_date_obj: "{{ expiry_date | ansible.builtin.to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"
#                                                      "expiry_date": "2024-04-11T00:43:18Z"


    - name: 05a - Debug expiry_date_obj
      debug:
        msg: "expiry_date_obj is of type {{ expiry_date_obj.__class__.__name__ }} and value {{ expiry_date_obj }}"

    - name: 06 - Obtain the Current Date Time
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: 06a - Debug current_date
      debug:
        msg: "current_date is of type {{ current_date.__class__.__name__ }} and value {{ current_date }}"


    - name: 07 - Convert Current Date Time string to DateTime Object
      set_fact:
        current_date_obj: "{{ current_date | ansible.builtin.to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"

    - name: 07a - Debug current_date_obj
      debug:
        msg: "current_date_obj is of type {{ current_date_obj.__class__.__name__ }} and value {{ current_date_obj }}"

    - name: 08 - Calculate difference between expiry date and today
      set_fact:
        days_until_expiry: "{{ (expiry_date_obj - current_date_obj).days }}"

    - name: 08a - Debug days_until_expiry
      debug:
        var: days_until_expiry

    - name: 09 - Check if the expiry date is before today or within 30 days
      debug:
        msg: >
          {% if days_until_expiry < 0 %}
            The certificate has already expired.
          {% elif days_until_expiry <= 30 %}
            The certificate will expire within the next 30 days.
          {% else %}
            The certificate is valid for more than 30 days.
          {% endif %}

