---
- hosts: all
  connection: httpapi
  tasks:
    - name: 01 - Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains

#    - name: 01a - Debug Domain Response
#      debug:
#        var: domains

    - name: 02 - Set domain_uuid
      set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"

# https://developer.cisco.com/docs/fmc-ansible/getravpngateway/#example
    - name: 03 - Execute 'getRaVpnGateway' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: response

    - name: 04 - Set expiry date fact
      set_fact:
        expiry_date: "{{ response['response']['items'][0]['certEnrollments'][0]['certificateInfo']['expiry'] }}"

# ChatGPT states we should remove this. 
#    - name: 05 - Convert Expiry Date string to DateTime Object
#      set_fact:
#        expiry_date_obj: "{{ expiry_date | ansible.builtin.to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"
#                                                      "expiry_date": "2024-04-11T00:43:18Z"

    - name: 05 - Convert Expiry Date string to Date Object
      set_fact:
        expiry_date_only: "{{ expiry_date | from_yaml | strftime('%Y-%m-%d') }}"

    - name: 05a - Debug expiry_date_only
      debug:
        msg: "expiry_date_only is {{ expiry_date_only }}"


    - name: 05a - Debug expiry_date_obj
      debug:
        msg: "expiry_date_obj is of type {{ expiry_date_obj.__class__.__name__ }} and value {{ expiry_date_obj }}"

    - name: 06 - Obtain the Current Date Time
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: 06a - Debug current_date
      debug:
        msg: "current_date is of type {{ current_date.__class__.__name__ }} and value {{ current_date }}"


    - name: 07 - Convert Current Date Time string to DateTime Object
      set_fact:
        current_date_obj: "{{ current_date | ansible.builtin.to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"

    - name: 07a - Debug current_date_obj
      debug:
        msg: "current_date_obj is of type {{ current_date_obj.__class__.__name__ }} and value {{ current_date_obj }}"

    - name: 08 - Calculate difference between expiry date and today
      set_fact:
        days_until_expiry: "{{ (expiry_date_obj - current_date_obj).days }}"

    - name: 08a - Debug days_until_expiry
      debug:
        var: days_until_expiry

    - name: 09 - Check if the expiry date is before today or within 30 days
      debug:
        msg: >
          {% if days_until_expiry < 0 %}
            The certificate has already expired.
          {% elif days_until_expiry <= 30 %}
            The certificate will expire within the next 30 days.
          {% else %}
            The certificate is valid for more than 30 days.
          {% endif %}

