- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Execute 'getAllDeviceSettings' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllDeviceSettings"
        path_params:
            domainUUID: "{{ domain[0].uuid }}"
        query_params:
#            offset: "{{ offset }}"
#            limit: "{{ limit }}"
            expanded: "{{ expanded }}"
