---
- name: Playbook to Push a RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: true

  tasks:
    - name: Do you need to delete the certificate ??? 
      ansible.builtin.pause:
        seconds: 5

    - name: 01 - Read the Firepower Creds from Vault
      community.hashi_vault.vault_kv2_get:
        path: "cred_lab_fmc"  
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: fmc_creds

    - name: 02 - Read the FTD RAVPN Certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "lab-ftd.theglens.net"         #p12_in_base64"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: acme_cert

    - name: 03 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: fmc_domains

    - name: 04 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ fmc_domains[0]['uuid'] }}"

    - name: 05 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
        register_as: ra_vpn_gateway



# FMC -> Objects -> PKI -> Cert Enrollment
    - name: 06 - Add Certificate to Objects > PKI > Cert Enrollment
      cisco.fmcansible.fmc_configuration:
        operation: "createVpnCertEnrollmentModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
        data:
            type: CertEnrollment
            enrollmentType: PKCS12
            overridable: True
            pkcs12Content: 
              base64Certificate: "{{ acme_cert.data.data.p12_in_base64 }}"
              passPhrase: 'cisco123'
            name: "AWX_imported_cert"
            description:  
            overrides: 
              target: 
                name: 'lab-ftd1'
                id: '769b0c9a-d0f9-11ee-8bb1-e2c15158e365'
                type: 'Device'


# FMC -> Objects -> PKI -> Cert Enrollment
    - name: AA - Execute 'getAllVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllVpnCertEnrollmentModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: all_vpn_cert_enrollments

    - name: AB - Execute 'getAllFTDRAVpnModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllFTDRAVpnModel"
        path_params:
          domainUUID: "{{ domain_uuid }}"
      register: all_ftd_vpn_models

    - name: Timmay HARD STOP this Playbook
      meta: end_play


#
#  This task likely needs to be removed
#
    - name: Execute 'updateVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "updateVpnCertEnrollmentModel"
        data:
          type: CertEnrollment
          enrollmentType: PKCS12
          overridable: true
          pkcs12Content:
            base64Certificate: "{{ acme_cert.data.data.p12_in_base64 }}"
            passPhrase: "cisco123"
          name: certName
          description: ""
          overrides:
            parent:
              id: 00505681-AEC9-0ed3-0000-137438953475
              type: CertEnrollment
            target:
              name: deviceName
              id: 93cdd824-6ef9-11ec-abd5-a12f5f15e4e2
              type: Device
        path_params:
          objectId: "00000000-0000-0ed3-0000-012884909581"
          domainUUID: "{{ domain_uuid }}"


    - name: Timmay HARD STOP this Playbook
      meta: end_play


    - name: 07 - Get Internal Certificate Status
      cisco.fmcansible.fmc_configuration:
        operation: "getAllInternalCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: internal_certs

#    - name: Print objectId
#      ansible.builtin.debug:
#        msg: "objectId is {{ ra_vpn_gateway }}"

 

#    - name: Execute 'getAllCertificateMapModel' operation
#      cisco.fmcansible.fmc_configuration:
#        operation: "getAllCertificateMapModel"
#        path_params:
#            domainUUID: "{{ domain_uuid }}"

#    - name: C1 - Execute 'getAllFTDRAVpnModel' operation
#      cisco.fmcansible.fmc_configuration:
#        operation: "getAllFTDRAVpnModel"
#        path_params:
#            domainUUID: "{{ domain_uuid }}"
#      register: all_ftd_vpn_models

#    - name: Debug the ra_vpn_gateway variable
#      ansible.builtin.debug:
#        var: ra_vpn_gateway
#
#    - name: Debug items in ra_vpn_gateway
#      ansible.builtin.debug:
#        msg: "Items: {{ ra_vpn_gateway.response.items }}"
#
#    - name: Debug items in ra_vpn_gateway
#      ansible.builtin.debug:
#        var: ra_vpn_gateway.response.items
#

#https://developer.cisco.com/docs/fmc-ansible/getftdravpnmodel/
#     objectId comes from task 05 - Get info from FMC getRaVpnGateway
#     Optimally we should be able to use the ra_vpn_gateway variable
#    - name: C2 - Execute 'getFTDRAVpnModel' operation
#      cisco.fmcansible.fmc_configuration:
#        operation: "getFTDRAVpnModel"
#        path_params:
#            objectId: "00000000-0000-0ed3-0000-004294970377"
#            domainUUID: "{{ domain_uuid }}"
#      register: ftd_vpn_model


# FMC -> Objects -> PKI -> Cert Enrollment
    - name: AA - Execute 'getAllVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllVpnCertEnrollmentModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: all_vpn_cert_enrollments


# https://developer.cisco.com/docs/fmc-ansible/updatevpncertenrollmentmodel
# FMC -> Objects -> PKI -> Cert Enrollment
    - name: BB - Execute 'updateVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "updateVpnCertEnrollmentModel"
        data:
            type: CertEnrollment
            enrollmentType: PKCS12
            overridable: True
            pkcs12Content: 
              base64Certificate: "{{ acme_cert.data.data.p12_in_base64 }}"
              passPhrase: 'cisco123'
            name: "ChangeThis"
            description:  
            overrides: 
              parent: 
                id: '00000000-0000-0ed3-0000-012884904511'
                type: 'CertEnrollment'
              target: 
                name: 'lab-ftd1'
                id: '769b0c9a-d0f9-11ee-8bb1-e2c15158e365'
                type: 'Device'
        path_params:
            objectId: "00000000-0000-0ed3-0000-012884904511"
            domainUUID: "{{ domain_uuid }}"

    - name: 10 - Push the RAVPN Gateway Certificate
      cisco.fmcansible.fmc_configuration:
        operation: "pushRaVpnGatewayCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
            raVpnGatewayUUID: "{{ ra_vpn_gateway['items'][0]['id'] }}"
        data:
            certificate: "{{ ravpn_cert.data.data.p12_in_base64 }}"
            passphrase: "{{ ravpn_cert.data.data.p12_passphrase }}"
      register: push_cert

    - name: Timmay HARD STOP this Playbook
      meta: end_play