---
- name: Playbook to Push a RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: true

  tasks:
    - name: 01 - Read the Firepower Creds from Vault
      community.hashi_vault.vault_kv2_get:
        path: "cred_lab_fmc"  
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: cred_lab_fmc


    - name: 02 - Read the FTD RAVPN Certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "lab-ftd.theglens.net"         #p12_in_base64"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: ravpn_cert


    - name: 03 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains


    - name: 04 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"

    - name: 05 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: ra_vpn_gateway

    - name: AA - Get Internal Certificate Status
      cisco.fmcansible.fmc_configuration:
        operation: "getAllInternalCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: internal_certs


    - name: XY - Execute 'updateVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "updateVpnCertEnrollmentModel"
        data:
            type: CertEnrollment
            enrollmentType: PKCS12
            overridable: True
            pkcs12Content: {'base64Certificate': "{{ ravpn_cert.data.data.p12_in_base64 }}" , 'passPhrase': 'passPhrase'}
            name: "Change This"
            description:  
            overrides: {'parent': {'id': '00505681-AEC9-0ed3-0000-137438953475', 'type': 'CertEnrollment'}, 'target': {'name': 'deviceName', 'id': '93cdd824-6ef9-11ec-abd5-a12f5f15e4e2', 'type': 'Device'}}
        path_params:
            # objectId: "{{ object_id }}"
            domainUUID: "{{ domain_uuid }}"




    - name: Timmay HARD STOP this Playbook
      meta: end_play

# https://developer.cisco.com/docs/fmc-ansible/getting-started/#task-operations
#
#

    - name: 06 - Push the RAVPN Gateway Certificate
      cisco.fmcansible.fmc_configuration:
        operation: "pushRaVpnGatewayCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
            raVpnGatewayUUID: "{{ ra_vpn_gateway['items'][0]['id'] }}"
        data:
            certificate: "{{ cert['data']['data']['p12_in_base64'] }}"
            passphrase: "{{ cert['data']['data']['p12_passphrase'] }}"
      register: push_cert




    - name: Timmay HARD STOP this Playbook
      meta: end_play

    - name: Timmay HARD STOP this Playbook
      meta: end_play
