---
- name: Playbook to Push a RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: false

  tasks:
    - name: 01 - Read the Firepower Creds from Vault
      community.hashi_vault.vault_kv2_get:
        path: "cred_lab_fmc"  
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: cred_lab_fmc


    - name: 02 - Read the FTD RAVPN Certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "lab-ftd.theglens.net"         #p12_in_base64"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: cert

    - name: Timmay HARD STOP this Playbook
      meta: end_play


#    - name: 03 - Set some Firepower Auth facts
#      ansible.builtin.set_fact:
#        ansible_username: "{{ cred_lab_fmc.data.data.ansible_username }}"
#        ansible_password: "{{ cred_lab_fmc.data.data.ansible_password }}"
#


    - name: 02 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains

    - name: 03 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"

    - name: 03 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: ra_vpn_gateway







    - name: Timmay HARD STOP this Playbook
      meta: end_play

    - name: Timmay HARD STOP this Playbook
      meta: end_play
