---
- name: Playbook to Push a RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: true

  tasks:
    - name: Do you need to delete the certificate ??? 
      ansible.builtin.pause:
        seconds: 5

    - name: 01 - Read the Firepower Creds from Vault
      community.hashi_vault.vault_kv2_get:
        path: "cred_lab_fmc"  
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: fmc_creds

    - name: 02 - Read the FTD RAVPN Certificate from Vault
      community.hashi_vault.vault_kv2_get:
        path: "lab-ftd.theglens.net"         #p12_in_base64"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method  }}" 
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
      register: ravpn_cert

    - name: 03 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
      register: fmc_domains

    - name: 04 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ fmc_domains[0]['uuid'] }}"

    - name: 05 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: ra_vpn_gateway

    - name: 06 - Add Certificate to Objects - PKI - Cert Enrollment
      cisco.fmcansible.fmc_configuration:
        operation: "createVpnCertEnrollmentModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
        data:
            type: CertEnrollment
            enrollmentType: PKCS12
            overridable: True
            pkcs12Content: 
              base64Certificate: "{{ ravpn_cert.data.data.p12_in_base64 }}"
              passPhrase: 'cisco123'
            name: "Imported_on_{{ ansible_date_time.date }}"
            description:  
            overrides: 
              target: 
                name: 'lab-ftd1'
                id: '769b0c9a-d0f9-11ee-8bb1-e2c15158e365'
                type: 'Device'

    - name: 07 - Get Internal Certificate Status
      cisco.fmcansible.fmc_configuration:
        operation: "getAllInternalCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: internal_certs

    - name: Print objectId
      ansible.builtin.debug:
        msg: "objectId is {{ ra_vpn_gateway }}"

    - name: AA - Execute 'getAllVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllVpnCertEnrollmentModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: all_vpn_cert_enrollments

    - name: Execute 'getAllCertificateMapModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllCertificateMapModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"

    - name: C1 - Execute 'getAllFTDRAVpnModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getAllFTDRAVpnModel"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: all_ftd_vpn_models

    - name: Debug the ra_vpn_gateway variable
      ansible.builtin.debug:
        var: ra_vpn_gateway

    - name: Debug items in ra_vpn_gateway
      ansible.builtin.debug:
        msg: "Items: {{ ra_vpn_gateway.response.items }}"

    - name: Debug items in ra_vpn_gateway
      ansible.builtin.debug:
        var: ra_vpn_gateway.response.items

    - name: C2 - Execute 'getFTDRAVpnModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "getFTDRAVpnModel"
        path_params:
            objectId: "{{ ra_vpn_gateway.response.items[0].policy.id }}"
            domainUUID: "{{ domain_uuid }}"
      register: ftd_vpn_model

    - name: C3 - Execute 'updateFTDRAVpnModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "updateFTDRAVpnModel"
        data:
            id: "00000000-0000-0ed3-0000-004294970377"
            name: "lab-ftd1_ravpn_policy"
            type: RAVpn
            description: SAMPLE PUT
            configureSSL: True
            configureIpsec: True
            accessInterfaceSettings:
              bypassACPolicyForDecryptTraffic: false
              interfaceSettings:
                - accessInterface:
                    name: "lab-ftd1_Outside"
                    id: "9a088322-d13c-11ee-8329-a8431f2f725e"
                    type: "SecurityZone"
                  configureInterfaceIDCertificate: false
                  enableSSL: true
                  enableIPSecIkev2: true
                  enableDTLS: true
              webPort: 443
              sslIdCertificate:
                type: CertEnrollment
                name: "Imported_on_2025-01-27"
                id: "00000000-0000-0ed3-0000-012884908222"
              ipsecIdCertificate:
                type: CertEnrollment
                name: "Imported_on_2025-01-27"
                id: "00000000-0000-0ed3-0000-012884908222"
              allowConnectionProfileSelection: true
              dtlsPort: 443
        path_params:
            objectId: "00000000-0000-0ed3-0000-004294970377"
            domainUUID: "{{ domain_uuid }}"

    - name: XY - Execute 'updateVpnCertEnrollmentModel' operation
      cisco.fmcansible.fmc_configuration:
        operation: "updateVpnCertEnrollmentModel"
        data:
            type: CertEnrollment
            enrollmentType: PKCS12
            overridable: True
            pkcs12Content: 
              base64Certificate: "{{ ravpn_cert.data.data.p12_in_base64 }}"
              passPhrase: 'cisco123'
            name: "ChangeThis"
            description:  
            overrides: 
              parent: 
                id: '00000000-0000-0ed3-0000-012884904511'
                type: 'CertEnrollment'
              target: 
                name: 'lab-ftd1'
                id: '769b0c9a-d0f9-11ee-8bb1-e2c15158e365'
                type: 'Device'
        path_params:
            objectId: "00000000-0000-0ed3-0000-012884904511"
            domainUUID: "{{ domain_uuid }}"

    - name: 10 - Push the RAVPN Gateway Certificate
      cisco.fmcansible.fmc_configuration:
        operation: "pushRaVpnGatewayCertificate"
        path_params:
            domainUUID: "{{ domain_uuid }}"
            raVpnGatewayUUID: "{{ ra_vpn_gateway['items'][0]['id'] }}"
        data:
            certificate: "{{ ravpn_cert.data.data.p12_in_base64 }}"
            passphrase: "{{ ravpn_cert.data.data.p12_passphrase }}"
      register: push_cert

    - name: Timmay HARD STOP this Playbook
      meta: end_play