---
#- name: Get Cert from Vault
#  hosts: localhost
#  gather_facts: false
#  tasks:


- name: Playbook to Push a RAVPN Gateway Certificate
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Read a kv2 secret from Vault (using token auth)
      community.hashi_vault.vault_kv2_get:
        url: "https://vault.theglens.net:8200"
        path: "lab-ftd.theglens.net/"         #p12_in_base64"
        auth_method: token
        token: "{{ ansible_password }}"
        engine_mount_point: "kv"
      register: response

    - name: 01 - Get FMC Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domains

    - name: 02 - Set domain_uuid
      ansible.builtin.set_fact:
        domain_uuid: "{{ domains[0]['uuid'] }}"

    - name: 03 - Get info from FMC getRaVpnGateway
      cisco.fmcansible.fmc_configuration:
        operation: "getRaVpnGateway"
        path_params:
            domainUUID: "{{ domain_uuid }}"
      register: ra_vpn_gateway








    - name: Timmay HARD STOP this Playbook
      meta: end_play

    - name: Timmay HARD STOP this Playbook
      meta: end_play

    - name: Timmay HARD STOP this Playbook
      meta: end_play
